FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block neutron_wireguard_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}

    {% set neutron_wireguard_agent_packages = [
        'wireguard-tools'
    ] %}

{% elif base_package_type == 'deb' %}

    {% set neutron_wireguard_agent_packages = [
        'wireguard'
    ] %}

{% endif %}

{{ macros.install_packages(neutron_wireguard_agent_packages | customizable("packages")) }}

{% block neutron_wireguard_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
