FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"

{% block doni_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='doni') }}

{% if base_package_type == 'rpm' %}
    {% set doni_base_packages = ['openstack-doni-common'] %}
{% elif base_package_type == 'deb' %}
    {% set doni_base_packages = ['doni-common'] %}
{% endif %}

{{ macros.install_packages(doni_base_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_doni_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_doni_extend_start \
    && mkdir -p /etc/doni \
    && chown -R doni: /etc/doni

{% block doni_base_footer %}{% endblock %}
