FROM {{ namespace }}/{{ image_prefix }}hacluster-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"

{% block hacluster_pacemaker_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set hacluster_pacemaker_packages = ['pacemaker'] %}
{{ macros.install_packages(hacluster_pacemaker_packages | customizable("packages")) }}

{% block hacluster_pacemaker_footer %}{% endblock %}
