FROM {{ namespace }}/{{ image_prefix }}glance-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"

{% block glance_registry_header %}{% endblock %}

{% block glance_registry_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER glance
