FROM {{ namespace }}/{{ image_prefix }}cyborg-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block cyborg_conductor_header %}{% endblock %}

{% block cyborg_conductor_footer %}{% endblock %}
{% block footer %}{% endblock %}
