FROM {{ namespace }}/{{ image_prefix }}qinling-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"

{% block qinling_engine_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% block qinling_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER qinling
