FROM {{ namespace }}/{{ image_prefix }}doni-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block doni_worker_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set doni_worker_packages = [] %}
{% elif base_package_type == 'deb' %}
    {% set doni_worker_packages = [] %}
{% endif %}

{% set doni_worker_pip_packages = [] %}

RUN {{ macros.install_pip(doni_worker_pip_packages | customizable("pip_packages")) }}

{{ macros.install_packages(doni_worker_packages | customizable("packages")) }}

{% block doni_worker_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER doni
