FROM {{ namespace }}/{{ image_prefix }}zun-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block zun_wsproxy_header %}{% endblock %}

{% block zun_wsproxy_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER zun
