FROM {{ namespace }}/{{ image_prefix }}aodh-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block aodh_listener_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block aodh_listener_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER aodh
