FROM {{ namespace }}/{{ image_prefix }}magnum-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block magnum_conductor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

ADD plugins-archive /
RUN cp /plugins/linux-{{ debian_arch }}/helm /usr/local/bin/helm

{% block magnum_conductor_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER magnum
