FROM {{ namespace }}/{{ image_prefix }}swift-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block swift_container_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block swift_container_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER swift
