---
- name: Template template_overrides.j2
  ansible.builtin.template:
    src: "{{ kolla_build_template_overrides_path }}"
    dest: /etc/kolla/template_overrides.j2
  when: kolla_build_template_overrides_path | length > 0

- name: Run kolla-build to template out dockerfiles
  ansible.builtin.command:
    cmd: >-
      {{ kolla_build_venv_path }}/bin/kolla-build --template-only
      --work-dir {{ kolla_build_logs_dir }}/work_dir

- name: Run kolla-build
  ansible.builtin.command:
    cmd: "{{ kolla_build_venv_path }}/bin/kolla-build"
