FROM {{ namespace }}/{{ image_prefix }}letsencrypt-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"

{% block letsencrypt_certbot_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set letsencrypt_certbot_packages = [
        'cronie',
        'python3-pip',
    ] %}
{% elif base_package_type == 'deb' %}
    {% set letsencrypt_certbot_packages = [
        'cron',
        'python3-pip',
    ] %}
{% endif %}
{{ macros.install_packages(letsencrypt_certbot_packages | customizable("packages")) }}

{% set letsencrypt_certbot_pip_packages = ['certbot'] %}
RUN {{ macros.install_pip(letsencrypt_certbot_pip_packages | customizable("pip_packages"), constraints = false) }}

{% block letsencrypt_certbot_footer %}{% endblock %}
{% block footer %}{% endblock %}
