FROM {{ namespace }}/{{ image_prefix }}gnocchi-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block gnocchi_statsd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block gnocchi_statsd_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER gnocchi
