FROM {{ namespace }}/{{ image_prefix }}congress-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"

{% block congress_datasource_header %}{% endblock %}

{% block congress_datasource_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER congress
