FROM {{ namespace }}/{{ image_prefix }}cyborg-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"

{% block cyborg_agent_header %}{% endblock %}
{% import "macros.j2" as macros with context %}

{% set cyborg_agent_packages = [
    'pciutils',
] %}

{{ macros.install_packages(cyborg_agent_packages | customizable("packages")) }}

{% if install_type == 'source' %}

{% set cyborg_agent_pip_packages = [ ] %}

RUN {{ macros.install_pip(cyborg_agent_pip_packages | customizable("pip_packages")) }} 

{% endif %}

{% block cyborg_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}
