FROM {{ namespace }}/{{ image_prefix }}ceph-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"

{% block ceph_mgr_header %}{% endblock %}

{% block ceph_mgr_footer %}{% endblock %}
{% block footer %}{% endblock %}
